#Requires -Version 5.1
<#
.SYNOPSIS
Installs the official WireGuard Windows client and optionally imports a tunnel.

.DESCRIPTION
This is a Windows client companion for wireguard-install.sh. The Linux script
creates the VPN server; this script installs WireGuard on Windows and can import
the client .conf file generated by wg-easy.
#>
[CmdletBinding()]
param(
    [ValidateSet("Menu", "Install", "Import", "InstallAndImport", "Uninstall")]
    [string]$Action = "Menu",

    [string]$ConfigPath,

    [string]$TunnelName,

    [string]$PackageVersion,

    [switch]$InstallTunnelService,

    [switch]$Force
)

$ErrorActionPreference = "Stop"

$PackageId = "WireGuard.WireGuard"

function Assert-Windows {
    if ([System.Environment]::OSVersion.Platform -ne [System.PlatformID]::Win32NT) {
        throw "This installer is for Windows only."
    }
}

function Test-Administrator {
    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($identity)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Assert-Administrator {
    if (-not (Test-Administrator)) {
        throw "Run PowerShell as Administrator and try again."
    }
}

function Get-WingetPath {
    $winget = Get-Command winget.exe -ErrorAction SilentlyContinue
    if (-not $winget) {
        throw "winget was not found. Install or update Microsoft App Installer, then run this script again."
    }

    return $winget.Source
}

function Invoke-NativeCommand {
    param(
        [Parameter(Mandatory = $true)]
        [string]$FilePath,

        [Parameter(Mandatory = $true)]
        [string[]]$Arguments
    )

    & $FilePath @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "Command failed with exit code $LASTEXITCODE`: $FilePath $($Arguments -join ' ')"
    }
}

function Join-OptionalPath {
    param(
        [string]$BasePath,
        [string]$ChildPath
    )

    if ([string]::IsNullOrWhiteSpace($BasePath)) {
        return $null
    }

    return Join-Path $BasePath $ChildPath
}

function Get-WireGuardExe {
    $candidates = @(
        (Join-OptionalPath $env:ProgramFiles "WireGuard\wireguard.exe"),
        (Join-OptionalPath ${env:ProgramFiles(x86)} "WireGuard\wireguard.exe")
    )

    foreach ($candidate in $candidates) {
        if ($candidate -and (Test-Path $candidate)) {
            return $candidate
        }
    }

    $command = Get-Command wireguard.exe -ErrorAction SilentlyContinue
    if ($command) {
        return $command.Source
    }

    throw "WireGuard executable was not found. Install WireGuard first."
}

function Get-SafeTunnelName {
    param([string]$SourcePath)

    $name = $TunnelName
    if ([string]::IsNullOrWhiteSpace($name)) {
        $fileName = [IO.Path]::GetFileName($SourcePath)
        if ($fileName.EndsWith(".conf.dpapi", [StringComparison]::OrdinalIgnoreCase)) {
            $name = $fileName.Substring(0, $fileName.Length - ".conf.dpapi".Length)
        } else {
            $name = [IO.Path]::GetFileNameWithoutExtension($SourcePath)
        }
    }

    $name = $name.Trim() -replace '[^A-Za-z0-9_.=-]', '-'
    if ([string]::IsNullOrWhiteSpace($name)) {
        throw "Could not determine a safe tunnel name. Use -TunnelName."
    }

    return $name
}

function Install-WireGuard {
    $winget = Get-WingetPath
    $arguments = @(
        "install",
        "--exact",
        "--id", $PackageId,
        "--source", "winget",
        "--accept-package-agreements",
        "--accept-source-agreements"
    )

    if ($PackageVersion) {
        $arguments += @("--version", $PackageVersion)
    }

    Write-Host "Installing WireGuard with winget..."
    Invoke-NativeCommand -FilePath $winget -Arguments $arguments

    $exe = Get-WireGuardExe
    Write-Host "WireGuard installed: $exe"
}

function Import-WireGuardConfig {
    if ([string]::IsNullOrWhiteSpace($ConfigPath)) {
        throw "Provide -ConfigPath with a WireGuard .conf file."
    }

    $resolvedPath = (Resolve-Path $ConfigPath).Path
    $isPlainConfig = $resolvedPath.EndsWith(".conf", [StringComparison]::OrdinalIgnoreCase)
    $isDpapiConfig = $resolvedPath.EndsWith(".conf.dpapi", [StringComparison]::OrdinalIgnoreCase)
    if (-not ($isPlainConfig -or $isDpapiConfig)) {
        throw "WireGuard client config must be a .conf file, or .conf.dpapi when using -InstallTunnelService."
    }

    $wireGuard = Get-WireGuardExe
    $safeName = Get-SafeTunnelName -SourcePath $resolvedPath

    if ($InstallTunnelService) {
        if ($Force) {
            & $wireGuard /uninstalltunnelservice $safeName 2>$null
        }

        Write-Host "Installing tunnel service: WireGuardTunnel`$$safeName"
        Invoke-NativeCommand -FilePath $wireGuard -Arguments @("/installtunnelservice", $resolvedPath)
        Write-Host "Tunnel service installed. Manage it from Services or the WireGuard UI."
        return
    }

    if ($isDpapiConfig) {
        throw ".conf.dpapi files can only be imported with -InstallTunnelService. Use a plain .conf file for WireGuard UI import."
    }

    $managerService = Get-Service -Name "WireGuardManager" -ErrorAction SilentlyContinue
    if (-not $managerService) {
        Write-Host "Installing WireGuard manager service..."
        Invoke-NativeCommand -FilePath $wireGuard -Arguments @("/installmanagerservice")
    } elseif ($managerService.Status -ne "Running") {
        Start-Service -Name "WireGuardManager"
    }

    $configDir = Join-Path $env:ProgramFiles "WireGuard\Data\Configurations"
    New-Item -ItemType Directory -Path $configDir -Force | Out-Null

    $plainTarget = Join-Path $configDir "$safeName.conf"
    $encryptedTarget = Join-Path $configDir "$safeName.conf.dpapi"

    if ((Test-Path $plainTarget) -or (Test-Path $encryptedTarget)) {
        if (-not $Force) {
            throw "Tunnel '$safeName' already exists. Re-run with -Force to replace it."
        }

        Remove-Item -Path $plainTarget, $encryptedTarget -Force -ErrorAction SilentlyContinue
    }

    Copy-Item -Path $resolvedPath -Destination $plainTarget -Force:$Force
    Start-Sleep -Seconds 2

    Start-Process -FilePath $wireGuard
    Write-Host "Imported tunnel '$safeName'. Open WireGuard and activate it when ready."
}

function Uninstall-WireGuard {
    $winget = Get-WingetPath
    Write-Host "Uninstalling WireGuard with winget..."
    Invoke-NativeCommand -FilePath $winget -Arguments @(
        "uninstall",
        "--exact",
        "--id", $PackageId,
        "--source", "winget",
        "--accept-source-agreements"
    )
}

function Show-Menu {
    while ($true) {
        Write-Host ""
        Write-Host "==============================="
        Write-Host " WireGuard Windows Installer"
        Write-Host "==============================="
        Write-Host "1) Install or upgrade WireGuard"
        Write-Host "2) Import WireGuard .conf"
        Write-Host "3) Install and import .conf"
        Write-Host "4) Uninstall WireGuard"
        Write-Host "5) Exit"
        Write-Host ""

        $choice = Read-Host "Select an option [1-5]"
        switch ($choice) {
            "1" { Install-WireGuard }
            "2" {
                if (-not $ConfigPath) { $script:ConfigPath = Read-Host "Path to .conf file" }
                Import-WireGuardConfig
            }
            "3" {
                if (-not $ConfigPath) { $script:ConfigPath = Read-Host "Path to .conf file" }
                Install-WireGuard
                Import-WireGuardConfig
            }
            "4" { Uninstall-WireGuard }
            "5" { return }
            default { Write-Warning "Invalid choice." }
        }
    }
}

Assert-Windows
Assert-Administrator

switch ($Action) {
    "Install" { Install-WireGuard }
    "Import" { Import-WireGuardConfig }
    "InstallAndImport" {
        Install-WireGuard
        Import-WireGuardConfig
    }
    "Uninstall" { Uninstall-WireGuard }
    default { Show-Menu }
}
